### ISSUE TITLE
Missing documentation tracker

### ISSUE THREAD

**Issue by mbaz** [mbaz/Gaston.jl#49]
- [x] Fillsteps
- [x] Grid
- [x] Stderr interaction
- [x] Start docs with tutorials for common usage
- [x] Provide motivation for using gnuplot
- [x] Add note about letting gnuplot's installer add it to the system path on windows.
- [x] Clarify how to run the tests
- [ ] Add reference documentation
